### ISSUE TITLE
Different sounds during the countdown "enhancement"

### ISSUE THREAD

**Issue by DJ-Dingo** [pibooth/pibooth-sound-effects#4]
It would be cool to, play different sounds during the countdown, like -> 3.wav. 2.wav, 1.wav.

It should only play the wav files that are available. have you set the countdown to 5 sec. But only has 4.wav, 2.wav, 1.wav it must be able to play them on 4, 2, 1 ... and nothing when there is no wav file with number that fits.

**Comment by werdeil** [comment]
Hi @DJ-Dingo, I just pushed commit https://github.com/pibooth/pibooth-sound-effects/commit/818541d10b775d75fb908d4afd7f25aba6c8185f which shall fit your need.

I will release a new version soon to include it.
